[Desktop Entry]
Encoding=UTF-8
Type=XSession
Exec=${STARTKDE_BINARY_DIR}/startkde
TryExec=${STARTKDE_BINARY_DIR}/startkde
DesktopNames=KDE
Name=Plasma Media Center
Name[ca]=Centre multimèdia del Plasma
Name[es]=Centro multimedia de Plasma
Name[nl]=Plasma mediacentrum
Name[pl]=Centrum multimedialne plazmy
Name[pt]=Centro Multimédia do Plasma
Name[pt_BR]=Plasma Media Center
Name[sv]=Plasma Media Center
Name[x-test]=xxPlasma Media Centerxx
Name[zh_CN]=Plasma 媒体中心
Comment=Plasma Media Center by KDE
Comment[ca]=Centre multimèdia del Plasma pel KDE
Comment[es]=Centro multimedia de Plasma, por KDE
Comment[nl]=Plasma mediacentrum door KDE
Comment[pl]=Centrum Multimedialne Plazmy dla KDE
Comment[pt]=Centro Multimédia do Plasma para o KDE
Comment[pt_BR]=Plasma Media Center do KDE
Comment[sv]=Plasma Media Center av KDE
Comment[x-test]=xxPlasma Media Center by KDExx
Comment[zh_CN]=KDE 的 Plasma 媒体中心
X-KDE-PluginInfo-Version=${PROJECT_VERSION}
