[Desktop Entry]
Encoding=UTF-8
Type=XSession
Exec=${STARTKDE_BINARY_DIR}/startkde
TryExec=${STARTKDE_BINARY_DIR}/startkde
DesktopNames=KDE
Name=Plasma Media Center
Name[ar]=مركز وسائط بلازما
Name[bs]=Plasma Media Center
Name[ca]=Centre multimèdia del Plasma
Name[ca@valencia]=Centre multimèdia del Plasma
Name[cs]=Multimediální centrum Plasma
Name[da]=Plasma Mediecenter
Name[de]=Plasma-Mediencenter
Name[el]=Plasma Media Center
Name[en_GB]=Plasma Media Centre
Name[es]=Plasma Media Center
Name[et]=Plasma meediakeskus
Name[fi]=Plasma-mediakeskus
Name[fr]=Centre multimédia pour Plasma
Name[gl]=Centro Multimedia de Plasma
Name[hu]=Plasma médiaközpont
Name[id]=Plasma Media Center
Name[it]=Plasma Media Center
Name[km]=មជ្ឈមណ្ឌល​មេឌៀ​ប្លាស្មា
Name[lt]=Plasma Media centras
Name[lv]=Plasma multivides centrs
Name[mr]=प्लाज्मा मीडिया सेंटर
Name[nl]=Plasma mediacentrum
Name[pl]=Centrum multimedialne plazmy
Name[pt]=Centro Multimédia do Plasma
Name[pt_BR]=Plasma Media Center
Name[sk]=Plasma Media Center
Name[sl]=Predstavnostno središče Plasma
Name[sv]=Plasma Media Center
Name[tr]=Plasma Ortam Merkezi
Name[ug]=پلازما ۋاسىتە مەركىزى
Name[uk]=Медіацентр Плазми
Name[x-test]=xxPlasma Media Centerxx
Name[zh_TW]=Plasma 媒體中心
Comment=Plasma Media Center by KDE
Comment[ca]=Centre multimèdia del Plasma pel KDE
Comment[da]=Plasma Mediecenter af KDE
Comment[en_GB]=Plasma Media Centre by KDE
Comment[es]=Centro multimedia de Plasma, por KDE
Comment[fi]=KDE:n tekemä Plasma-mediakeskus
Comment[it]=Plasma Media Center di KDE
Comment[nl]=Plasma mediacentrum door KDE
Comment[pl]=Centrum Multimedialne Plazmy dla KDE
Comment[pt]=Centro Multimédia do Plasma para o KDE
Comment[pt_BR]=Plasma Media Center do KDE
Comment[sk]=Plasma Media Center od KDE
Comment[sv]=Plasma Media Center av KDE
Comment[uk]=Медіацентр Плазми від KDE
Comment[x-test]=xxPlasma Media Center by KDExx
X-KDE-PluginInfo-Version=${PROJECT_VERSION}
