[Desktop Entry]
Encoding=UTF-8
Type=XSession
Exec=${STARTKDE_BINARY_DIR}/startkde
TryExec=${STARTKDE_BINARY_DIR}/startkde
DesktopNames=KDE
Name=Plasma Media Center
Name[ar]=مركز وسائط بلازما
Name[bs]=Plasma Media Center
Name[ca]=Centre multimèdia del Plasma
Name[ca@valencia]=Centre multimèdia del Plasma
Name[cs]=Multimediální centrum Plasma
Name[da]=Plasma Mediecenter
Name[de]=Plasma-Mediencenter
Name[el]=Plasma Media Center
Name[en_GB]=Plasma Media Centre
Name[es]=Plasma Media Center
Name[et]=Plasma meediakeskus
Name[fi]=Plasma-mediakeskus
Name[fr]=Centre multimédia pour Plasma
Name[gl]=Centro Multimedia de Plasma
Name[hu]=Plasma médiaközpont
Name[id]=Plasma Media Center
Name[it]=Plasma Media Center
Name[km]=មជ្ឈមណ្ឌល​មេឌៀ​ប្លាស្មា
Name[lt]=Plasma Media centras
Name[lv]=Plasma multivides centrs
Name[mr]=प्लाज्मा मीडिया सेंटर
Name[nl]=Plasma mediacentrum
Name[pl]=Centrum multimedialne plazmy
Name[pt]=Centro Multimédia do Plasma
Name[pt_BR]=Plasma Media Center
Name[sk]=Plasma Media Center
Name[sl]=Predstavnostno središče Plasma
Name[sv]=Plasma Media Center
Name[tr]=Plasma Ortam Merkezi
Name[ug]=پلازما ۋاسىتە مەركىزى
Name[uk]=Медіацентр Плазми
Name[x-test]=xxPlasma Media Centerxx
Name[zh_TW]=Plasma 媒體中心
Comment=Plasma Media Center by KDE
X-KDE-PluginInfo-Version=${PROJECT_VERSION}
